# i think here i have to run the three dockerfiles services (ngix, mariadb, wordpress)

# how to write docker-compose ????
# version: ???

# Docker network handles DNS

# TODO		volumes
# TODO		network link
# TODO		environment var

services:
  mariadb:
    container_name: mariadb
    build:
      dockerfile: Dockerfile
      context: ./requirements/mariadb/
    environment:
      - MYSQL_ROOT_PASSWORD
      - WORDPRESS_DB_NAME
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - mariadb-data:/var/lib/mysql # -> This directory contains all the database files
    networks:
      - br_net
    restart: unless-stopped


  wordpress:
    container_name: wordpress
    build:
      dockerfile: Dockerfile
      context: ./requirements/wordpress/
    depends_on:
      - mariadb
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
    volumes:
      - wordpress-data:/var/www/html/wordpress # -> here persists all core files, themes, plugins, and uploads.
    networks:
      - br_net
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile
      context: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - 443:443
    environment:
      - DOMAIN_NAME
    volumes:
      - wordpress-data:/var/www/html/wordpress:ro
    networks:
      - br_net
    restart: unless-stopped

volumes:
  mariadb-data:
  wordpress-data:

networks:
  br_net:
    driver: bridge
