# i think here i have to run the three dockerfiles services (ngix, mariadb, wordpress)

# how to write docker-compose ????
# version: ???

# Docker network handles DNS

# TODO		volumes
# TODO		network link
# TODO		environment var

services:

  mariadb:
    build:
      dockerfile: Dockerfile
      context: ./requirements/mariadb/
    environment:
      - WORDPRESS_DB_NAME
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - mariadb-data:/var/lib/mysql # -> This directory contains all the database files
    networks:
      - br_net


  wordpress:
    build:
      dockerfile: Dockerfile
      context: ./requirements/wordpress/
    depends_on:
      - mariadb
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
    volumes:
      - wordpress-data:/var/www/html/wordpress # -> here persists all core files, themes, plugins, and uploads.
    networks:
      - br_net

#	you most config the nginx to sync with the wordpress
#   nginx:
#     build:
#       dockerfile: Dockerfile
#       context: ./requirements/nginx/
#     ports:
#       - "9000:9000"
#     depends_on:
#       - wordpress

volumes:
  mariadb-data:
  wordpress-data:

networks:
  br_net:
    driver: bridge
