# i think here i have to run the three dockerfiles services (ngix, mariadb, wordpress)

# how to write docker-compose ????
# version: ???

# Docker network handles DNS

# TODO		volumes
# TODO		network link
# TODO		environment var

# field
# key
# value

services:

  mariadb:
    build:
      dockerfile: Dockerfile
      context: ./requirements/mariadb/
    environment:
      # sql
      - MYSQL_USER
      - MYSQL_HOSTNAME
      - MYSQL_PASSWORD
      # wordpress
      - WORDPRESS_USER  # used
      - WORDPRESS_PASS  # used
      - WORDPRESS_DB_NAME # used
    volumes:
      - mariadb-data:/var/lib/mysql # -> This directory contains all the database files
    networks:
      - br_net

#   wordpress:
#     build:
#       dockerfile: Dockerfile
#       context: ./requirements/wordpress/
#     depends_on:
#       mariadb:
#         condition: service_healthy
#     environment:
#       - DOMAIN_NAME
#       - ADMIN_USER
#       - ADMIN_PASSWORD

#     volumes:
#       - wordpress-data:/etc/data

#     networks:
#       - br_net


#   nginx:
#     build:
#       dockerfile: Dockerfile
#       context: ./requirements/nginx/
#     ports:
#       - "9000:9000"
#     depends_on:
#       - wordpress

volumes:
  mariadb-data:
  wordpress-data:

networks:
  br_net:
    driver: bridge
