# i think here i have to run the three dockerfiles services (ngix, mariadb, wordpress)

# how to write docker-compose ????
# version: ???

# Docker network handles DNS

# TODO		volumes
# TODO		network link
# TODO		environment var

services:
  mariadb:
    container_name: mariadb
    build:
      dockerfile: Dockerfile
      context: ./requirements/mariadb/
    environment:
      - MYSQL_ROOT_PASSWORD
      - WORDPRESS_DB_NAME
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - mariadb-data:/var/lib/mysql # >>> This directory contains all the database files
    networks:
      - br_net
    restart: unless-stopped


  wordpress:
    container_name: wordpress
    build:
      dockerfile: Dockerfile
      context: ./requirements/wordpress/
    depends_on:
      - mariadb
    environment:
      - DOMAIN_NAME # done
      - MYSQL_USER # not yet
      - MYSQL_PASSWORD # not yet
      - WP_DB_HOST
      - WP_DB_NAME
      - WR_DB_USER
      - WP_DB_PASSWORD
      - WP_ADMIN_USER # done
      - WP_ADMIN_PASSWORD # done
      - WP_ADMIN_EMAIL
      - WP_USER
      - WP_USER_PASSWORD
      - WP_USER_EMAIL
    volumes:
      - wordpress-data:/var/www/html/wordpress # >>> here persists all core files, themes, plugins, and uploads.
    networks:
      - br_net
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile
      context: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - 443:443
    environment:
      - DOMAIN_NAME
    volumes:
      - wordpress-data:/var/www/html/wordpress:ro
    networks:
      - br_net
    restart: unless-stopped

volumes:
  mariadb-data:
    driver: local   # >>> docker will use the local driver
    driver_opts:
      type: none    # >>> filesystem type
      o: bind       # >>> (options) bind mount local path to the continer
      device: /home/yanflous/data/mariadb   # >>> path to store data to
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yanflous/data/wordpress

networks:
  br_net:
    driver: bridge
